name: components_codelab
description: An AngularDart app that simulates a lottery
version: 0.0.1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.3
  intl: ^0.16.1

dev_dependencies:
  angular_test: ^3.0.0
  build_runner: ^1.7.0
  build_test: ^1.3.6
  build_web_compilers: ^2.4.0
  test: ^1.6.3
