name: Jekyll CI
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          cache: yarn
      - run: yarn install
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
      - name: Setup Ruby and cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: git submodule update --init --recursive
      - run: dart run grinder build --refresh=all
