name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^6.0.1

# #docregion dev_dependencies, build-dependencies
dev_dependencies:
  # #enddocregion build-dependencies
  angular_test: ^3.0.0
  # #docregion build-dependencies
  build_runner: ^1.7.0
  build_test: ^1.3.6
  build_web_compilers: ^2.4.0
  # #enddocregion build-dependencies
  test: ^1.6.3
# #enddocregion dev_dependencies
